#!/usr/bin/env sh

# Terminates already running stalonetray instances
killall -q stalonetray

# Wait until all the processes are dead
while pgrep -x stalonetray >/dev/null; do sleep 1; done

# Launch stalonetray
stalonetray &

exit 0
