#!/bin/sh
# Kenielf's Smart Youtube URL Player Helper
# By default it depends on xclip, sed, grep, mpv, xdotool, ps, notify-send

###--- VARIABLES ---###
SEL=$(xclip -o sel clipboard | sed -e 's/^/\"/g' -e 's/$/\"/g')
WIN="$(ps -e | grep $(xdotool getwindowpid $(xdotool getwindowfocus)) | grep -v grep)"
YTB_URL="youtube"
TWT_URL="twitch"
WIN_RXP="firefox"

###--- MAIN ---###
#printf "\"$SEL\"\n\"$WIN\"\n" # Debugging
if [ "${SEL#*$YTB_URL}" != "$SEL" ]; then
    URL=$(echo $SEL | sed -e 's/"//g')
    mpv $URL mpv $URL & >/dev/null
    notify-send "Playing from clipboard." $SEL
elif [ "${SEL#*$TWT_URL}" != "$SEL" ]; then
    URL=$(echo $SEL | sed -e 's/"//g')
    mpv $URL mpv $URL & >/dev/null
    notify-send "Playing from clipboard." $SEL
else
    if [ "${WIN#*$WIN_RXP}" != "$WIN" ]; then
        sleep 1; xdotool getactivewindow key ctrl+l sleep 2 key ctrl+c key F6; sleep 1
        SEL=$(xclip -o sel clipboard | sed -e 's/^/\"/g' -e 's/$/\"/g')
        if [ "${SEL#*$YTB_URL}" != "$SEL" ]; then
            URL=$(xclip -o sel clipboard | sed -e 's/^/\"/g' -e 's/$/\"/g' | sed -e 's/"//g')
            mpv $URL mpv $URL & >/dev/null
            notify-send "Playing from browser." $SEL
        elif [ "${SEL#*$TWT_URL}" != "$SEL" ]; then
            URL=$(xclip -o sel clipboard | sed -e 's/^/\"/g' -e 's/$/\"/g' | sed -e 's/"//g')
            mpv $URL mpv $URL & >/dev/null
            notify-send "Playing from browser." $SEL
        else
            printf "Your clipboard cannot be processed.\n"
            notify-send "Your clipboard cannot be processed." "Error playing: $SEL"
            exit 1
        fi
    else
        printf "Your clipboard cannot be processed.\n"
        notify-send "Your clipboard cannot be processed." "Error playing: $SEL"
        exit 1
    fi
fi
