#!/usr/bin/env sh
# vi: ft=sh
# shellcheck disable=SC2086 # NOTE: Intentional word splitting
# Usage: test-notification

# Check for dependencies
ksdeps "notify-send" || exit "${?}"

# Get the icons directory
icons_dir="/usr/share/icons/hicolor/64x64/stock/"
if [ ! -d "${icons_dir}" ]; then
    kserr "icons: missing icons folder -- notification will be sent without explicit icons!"
else
    ksdebug "icons: found '\e[32m${icons_dir}\e[00m' -- notifications will use icons!"
    icon_args="-i preferences-system-notifications"
fi

# Send the actual notification
notify-send \
    --urgency=normal \
    --expire-time=3000 \
    ${icon_args} \
    "Test Notification" \
    "This is the body of the test notification"

